[workspace]
resolver = "2"
members = [
    "crates/airproto",
    "crates/airbus",
    "crates/aircomp",
    "crates/airkit-theme",
    "crates/airkit-ui",
    "crates/airshell",
    "crates/airwm",
    "apps/airfiles",
    "apps/airterm",
    "apps/airsettings",
    "apps/airsetup",
    "apps/airdemo",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["AirOS Contributors"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "2"
rmp-serde = "1"
tokio = { version = "1", features = ["net", "io-util", "macros", "rt-multi-thread", "test-util", "time"] }
tempfile = "3"
wgpu = "22"
