[package]
name = "aircomp"
version.workspace = true
edition.workspace = true

[[bin]]
name = "aircomp"
path = "src/main.rs"

[lib]
name = "aircomp"
path = "src/lib.rs"

[dependencies]
airproto = { path = "../airproto" }
tokio = { workspace = true }
wgpu = { workspace = true }
winit = "0.30"
pollster = "0.3"

[dev-dependencies]
tempfile = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.30", features = ["wayland", "x11"] }
